#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate a human-readable MD report from scoring results for districts and MOs.

Inputs (CSVs generated by _13_generate_final_statistics.py):
- data/output/scoring_districts.csv
- data/output/scoring_mos.csv

Output:
- data/output/scoring_report.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from datetime import datetime
from typing import List, Optional

import numpy as np
import pandas as pd


sys.path.insert(0, str(Path(__file__).parent.parent))
DATA_DIR = Path(__file__).parent.parent.parent / "data"
OUTPUT_DIR = DATA_DIR / "output"

# ─── Configuration (must match _13_generate_final_statistics.py) ─────────────

PLANNED_WEIGHTS = {
    "1.1": 20,
    "1.2": 5,
    "2.1": 15,
    "2.2": 5,
    "2.3": 10,
    "3.1": 10,
    "4.3": 5,
}
PLANNED_TOTAL_WEIGHT = sum(PLANNED_WEIGHTS.values())

# Human-readable criterion labels
CRITERIA_LABELS = {
    "1.1": "Плотность конкурентов",
    "1.2": "Выживаемость бизнеса",
    "2.1": "Численность ЦА (30–64)",
    "2.2": "Доля женщин труд. возр.",
    "2.3": "Рост населения 2018–2025",
    "3.1": "Средняя зарплата",
    "4.3": "Ввод жилья 2021–2023",
}

# Thresholds for score interpretation
SCORING_THRESHOLDS = {
    "1.1": "3 = > 40 тыс. чел. на мастерскую · 2 = 25–40 тыс. · 1 = < 25 тыс.",
    "1.2": "3 = > 70% работающих · 2 = 60–70% · 1 = < 60%",
    "2.1": "3 = > 200 тыс. чел. · 2 = 100–200 тыс. · 1 = < 100 тыс.",
    "2.2": "3 = верхняя треть районов · 2 = средняя треть · 1 = нижняя треть",
    "2.3": "3 = рост > 10% · 2 = 0–10% · 1 = убыль",
    "3.1": "3 = > 140 тыс. ₽ · 2 = 120–140 тыс. ₽ · 1 = < 120 тыс. ₽",
    "4.3": "3 = > 500 тыс. кв. м · 2 = 200–500 тыс. · 1 = < 200 тыс.",
}


# ─── Formatting ───────────────────────────────────────────────────────────────

def fmt_int(x) -> str:
    """123456 → '123 456'."""
    if pd.isna(x):
        return "—"
    return f"{int(round(float(x))):,}".replace(",", " ")


def fmt_pct(x, digits: int = 1) -> str:
    """0.1506 → '+15.1%' (for changes)."""
    if pd.isna(x):
        return "—"
    v = float(x) * 100
    sign = "+" if v > 0 else ""
    return f"{sign}{v:.{digits}f}%"


def fmt_pct_abs(x, digits: int = 1) -> str:
    """0.65 → '65%' (for rates/shares, no sign)."""
    if pd.isna(x):
        return "—"
    return f"{float(x) * 100:.{digits}f}%"


def fmt_float(x, digits: int = 1) -> str:
    if pd.isna(x):
        return "—"
    return f"{float(x):.{digits}f}"


def fmt_score(x) -> str:
    """Score 1/2/3 → emoji indicator for readability."""
    if pd.isna(x):
        return "—"
    v = int(x)
    if v == 3:
        return "🟢 3"
    if v == 2:
        return "🟡 2"
    return "🔴 1"


def fmt_white_spot(flag: str) -> str:
    labels = {
        "high": "🔴 Высокий — нет мастерских, > 50 тыс. жителей",
        "medium": "🟡 Средний — 0–1 мастерских, 30–50 тыс. жителей",
        "normal": "Обычный",
        "unknown": "—",
    }
    return labels.get(flag, flag)


def fmt_scale_priority(is_low: bool) -> str:
    return "⚠️ Малый рынок (< 30 тыс.)" if is_low else "Достаточный"


# ─── Report generation ────────────────────────────────────────────────────────

def generate_report(
    district_df: pd.DataFrame,
    mo_df: pd.DataFrame,
    top_districts: int,
    top_mos_per_district: int,
    min_district_score: Optional[float],
) -> str:
    now = datetime.now().strftime("%d.%m.%Y %H:%M")
    L: List[str] = []

    # ── Title ──
    L.append("# Скоринг локаций для ювелирной мастерской")
    L.append("")
    L.append(f"> Дата расчёта: {now}  ")
    L.append(f"> Модель: двухэтапная (вариант A)  ")
    L.append(f"> Город: Санкт-Петербург")
    L.append("")

    # ── How to read the report ──
    L.append("## Как читать этот отчёт")
    L.append("")
    L.append("Отчёт выбирает лучшие районы и муниципальные округа (МО) для открытия "
             "ювелирной мастерской в два этапа:")
    L.append("")
    L.append("1. **Этап 1 — Районы.** Каждый из 18 районов получает баллы (от 1 до 3) "
             "по семи критериям. Баллы умножаются на вес критерия и складываются в итоговый рейтинг. "
             "Чем выше рейтинг — тем привлекательнее район.")
    L.append("2. **Этап 2 — МО внутри лучших районов.** Внутри отобранных районов ранжируются "
             "муниципальные округа по уровню конкуренции: чем больше жителей на одну мастерскую, "
             "тем ниже конкуренция и выше потенциал.")
    L.append("")
    L.append("**Шкала баллов:** 🟢 3 — лучший результат · 🟡 2 — средний · 🔴 1 — худший.")
    L.append("")

    # ── Stage 1 — Criteria and weights ──
    L.append("---")
    L.append("")
    L.append("## Этап 1. Рейтинг районов")
    L.append("")
    L.append("### Критерии оценки")
    L.append("")
    L.append("| № | Критерий | Вес | Что измеряет | Шкала баллов |")
    L.append("|---|---|---:|---|---|")
    for k, w in PLANNED_WEIGHTS.items():
        label = CRITERIA_LABELS[k]
        thresh = SCORING_THRESHOLDS[k]
        L.append(f"| {k} | {label} | {w}% | см. ниже | {thresh} |")
    L.append("")

    L.append(f"**Сумма весов доступных критериев:** {PLANNED_TOTAL_WEIGHT}% из 100%. "
             f"Остальные 30% — критерии, для которых пока нет данных: "
             f"пешеходный трафик, транспортная доступность, парковка, co-tenancy.")
    L.append("")
    L.append("**Формула итогового рейтинга:**  ")
    L.append("Рейтинг = сумма (балл × вес) / сумма весов посчитанных критериев.  ")
    L.append("Если какой-то показатель недоступен для района, он исключается и из числителя, и из знаменателя.")
    L.append("")

    # ── District table ──
    df = district_df.sort_values("district_rank", ascending=True)
    if min_district_score is not None:
        df_sel = df[df["district_score"] >= min_district_score].copy()
        rule_text = f"рейтинг ≥ {min_district_score}"
    else:
        df_sel = df.head(top_districts).copy()
        rule_text = f"топ-{top_districts} по рейтингу"

    L.append(f"### Результаты ({rule_text})")
    L.append("")
    L.append(f"Отобрано **{len(df_sel)}** районов из 18 для детального анализа на этапе 2.")
    L.append("")

    # Main table — rating + scores
    L.append("| Место | Район | Рейтинг | 1.1 Конкуренция | 1.2 Выживаемость | 2.1 ЦА 30–64 | 2.2 Женщины | 2.3 Рост | 3.1 Зарплата | 4.3 Жильё |")
    L.append("|---:|---|---:|---|---|---|---|---|---|---|")

    for _, r in df_sel.iterrows():
        L.append(
            f"| {int(r['district_rank'])} "
            f"| **{r['district_name']}** "
            f"| **{fmt_float(r['district_score'], 2)}** "
            f"| {fmt_score(r['score_1_1'])} "
            f"| {fmt_score(r['score_1_2'])} "
            f"| {fmt_score(r['score_2_1'])} "
            f"| {fmt_score(r['score_2_2'])} "
            f"| {fmt_score(r['score_2_3'])} "
            f"| {fmt_score(r['score_3_1'])} "
            f"| {fmt_score(r['score_4_3'])} |"
        )
    L.append("")

    # Detail — metrics in natural units
    L.append("### Показатели в натуральных единицах")
    L.append("")
    L.append(
        "| Место | Район | Население | Мастерских | Жителей на мастерскую | "
        "Выживаемость | ЦА 30–64, чел. | Доля женщин | "
        "Рост населения | Зарплата, ₽ | Ввод жилья, тыс. кв. м |"
    )
    L.append("|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")

    for _, r in df_sel.iterrows():
        L.append(
            f"| {int(r['district_rank'])} "
            f"| {r['district_name']} "
            f"| {fmt_int(r['population'])} "
            f"| {fmt_int(r['workshops_working'])} "
            f"| {fmt_int(r['people_per_workshop_smoothed'])} "
            f"| {fmt_pct_abs(r['survival_rate'], 0) if pd.notna(r['survival_rate']) else '—'} "
            f"| {fmt_int(r['target_30_65'])} "
            f"| {fmt_pct_abs(r['female_working_share'])} "
            f"| {fmt_pct(r['growth_2018_2025'])} "
            f"| {fmt_int(r['salary'])} "
            f"| {fmt_float(r['housing_2021_2023'], 1)} |"
        )
    L.append("")

    # Column explanations
    L.append("<details><summary>Пояснения к столбцам</summary>")
    L.append("")
    L.append("- **Жителей на мастерскую** — население района ÷ (работающие мастерские + 0.5). "
             "Чем больше — тем ниже конкуренция.")
    L.append("- **Выживаемость** — доля работающих ювелирных мастерских от общего числа "
             "(включая закрытые). ⚠️ Выборка мала (1–39 организаций на район), "
             "показатель может быть шумным.")
    L.append("- **ЦА 30–64** — численность жителей в возрасте 30–64 года (основная целевая аудитория).")
    L.append("- **Доля женщин** — женщины трудоспособного возраста / всё население района. "
             "Женская аудитория чаще обращается в ювелирные мастерские.")
    L.append("- **Рост населения** — изменение за 2018–2025 гг. Растущий район = растущий спрос.")
    L.append("- **Зарплата** — средняя заработная плата по предприятиям района. "
             "⚠️ Отражает доходы работающих *в* районе, а не *живущих* в нём.")
    L.append("- **Ввод жилья** — суммарный ввод нового жилья за 2021–2023 гг. "
             "Новостройки = приток жителей.")
    L.append("")
    L.append("</details>")
    L.append("")

    # ── Stage 2 — MOs ──
    L.append("---")
    L.append("")
    L.append("## Этап 2. Муниципальные округа внутри лучших районов")
    L.append("")
    L.append("Внутри каждого отобранного района МО ранжируются по показателю "
             "«жителей на одну мастерскую» — чем выше значение, тем меньше конкуренция.")
    L.append("")
    L.append("**Что означают пометки:**")
    L.append("- **Приоритет проверки** — в МО мало или нет мастерских при большом населении. "
             "Это может быть «белое пятно» (реальная возможность) или неполнота данных. "
             "Требуется ручная проверка на картах / в каталогах.")
    L.append("- **Масштаб рынка** — МО с населением < 30 тыс. считаются малыми: "
             "клиентская база может быть недостаточной для окупаемости.")
    L.append("")

    selected_ids = df_sel["district_id"].astype(int).tolist()
    mo_sel = mo_df[mo_df["district_id"].isin(selected_ids)]

    if mo_sel.empty:
        L.append("_Нет данных по МО для выбранных районов._")
    else:
        for did in selected_ids:
            row_d = df_sel[df_sel["district_id"] == did].iloc[0]
            name = row_d["district_name"]
            rank = int(row_d["district_rank"])
            score = fmt_float(row_d["district_score"], 2)

            L.append(f"### {rank}. {name} (рейтинг района: {score})")
            L.append("")

            sub = (
                mo_sel[mo_sel["district_id"] == did]
                .sort_values(["mo_people_per_workshop_smoothed", "population"],
                             ascending=[False, False])
                .head(top_mos_per_district)
            )

            L.append(
                "| № | Муниципальный округ | Население | Мастерских | "
                "Жителей на мастерскую | Приоритет проверки | Масштаб рынка |"
            )
            L.append("|---:|---|---:|---:|---:|---|---|")

            for i, (_, r) in enumerate(sub.iterrows(), 1):
                mo_name = str(r["mo_name"]) if pd.notna(r.get("mo_name")) else f"МО #{int(r['mo_id'])}"
                L.append(
                    f"| {i} "
                    f"| {mo_name} "
                    f"| {fmt_int(r['population'])} "
                    f"| {int(r['workshops_working'])} "
                    f"| {fmt_int(r['mo_people_per_workshop_smoothed'])} "
                    f"| {fmt_white_spot(r['white_spot_flag'])} "
                    f"| {fmt_scale_priority(bool(r['low_priority_by_scale']))} |"
                )
            L.append("")

    # ── Model limitations ──
    L.append("---")
    L.append("")
    L.append("## Ограничения и оговорки")
    L.append("")
    L.append("Эта модель — инструмент **грубого отсева**, а не финальное решение. "
             "Перед подписанием аренды обязателен этап полевых проверок (этап 3).")
    L.append("")
    L.append("**Что модель НЕ учитывает** (нет данных):")
    L.append("- Пешеходный и автомобильный трафик")
    L.append("- Расстояние до метро и остановок транспорта")
    L.append("- Наличие парковки")
    L.append("- Соседство с комплементарными бизнесами (свадебные салоны, бутики, ТЦ)")
    L.append("- Стоимость аренды")
    L.append("- Видимость и этажность помещения")
    L.append("")
    L.append("**Известные ограничения данных:**")
    L.append("- *Выживаемость (1.2)* — рассчитана по ювелирным мастерским (1–39 точек на район). "
             "Малая выборка → результат может быть случайным.")
    L.append("- *Зарплата (3.1)* — средняя зарплата по предприятиям района. "
             "Центральный район завышен из-за офисов, хотя большинство работников живут в других районах.")
    L.append("- *ЦА 30–64 (2.1)* — абсолютная численность, а не плотность в зоне доступности мастерской. "
             "Крупные районы получают преимущество.")
    L.append("")

    # ── Methodology (brief) ──
    L.append("---")
    L.append("")
    L.append("## Методология (кратко)")
    L.append("")
    L.append("**Формула рейтинга района:**  ")
    L.append("Рейтинг = Σ (балл × вес) / Σ весов посчитанных критериев")
    L.append("")
    L.append("**Формула ранжирования МО:**  ")
    L.append("Жителей на мастерскую = население МО / (работающие мастерские + 0.5)")
    L.append("")
    L.append("Подробная методика: см. документ «Критерии оценки районов и МО — двухэтапная модель A».")
    L.append("")

    return "\n".join(L)


# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate an MD report from scoring results (reads scoring_districts.csv and scoring_mos.csv)",
    )
    parser.add_argument("--top-districts", type=int, default=8,
                        help="Top-N districts for stage 2")
    parser.add_argument("--min-district-score", type=float, default=None,
                        help="Minimum district_score threshold for district selection")
    parser.add_argument("--top-mos-per-district", type=int, default=10,
                        help="How many MOs to display per district")
    parser.add_argument("--output", type=str, default=None,
                        help="Path to output file (default: data/output/scoring_report.md)")
    args = parser.parse_args()

    district_path = OUTPUT_DIR / "scoring_districts.csv"
    mo_path = OUTPUT_DIR / "scoring_mos.csv"

    if not district_path.exists():
        print(f"[error] File not found: {district_path}")
        print("         Run _13_generate_final_statistics.py first")
        return 1
    if not mo_path.exists():
        print(f"[error] File not found: {mo_path}")
        return 1

    district_df = pd.read_csv(district_path)
    mo_df = pd.read_csv(mo_path)

    report = generate_report(
        district_df=district_df,
        mo_df=mo_df,
        top_districts=args.top_districts,
        top_mos_per_district=args.top_mos_per_district,
        min_district_score=args.min_district_score,
    )

    out_path = Path(args.output) if args.output else OUTPUT_DIR / "scoring_report.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"[ok] Report: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
